# PyInstaller spec for Logitech Battery Monitor
# Produces a single-file Windows executable (no Python install required).

from PyInstaller.utils.hooks import collect_all, collect_submodules

block_cipher = None

# Collect entire bleak and pystray packages (they use dynamic imports)
bleak_d,  bleak_b,  bleak_h  = collect_all("bleak")
pystray_d, pystray_b, pystray_h = collect_all("pystray")

a = Analysis(
    ["../monitor.py"],
    pathex=[".."],
    binaries=bleak_b + pystray_b,
    datas=bleak_d + pystray_d,
    hiddenimports=(
        bleak_h + pystray_h
        + collect_submodules("bleak")
        + collect_submodules("pystray")
        + [
            "bleak.backends.winrt",
            "bleak.backends.winrt.client",
            "bleak.backends.winrt.scanner",
            "bleak.backends.winrt.utils",
            "pystray._win32",
            "PIL._imaging",
            "winreg",
        ]
    ),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "test", "unittest"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="LogitechBatteryMonitor",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,                    # no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="icon.ico",                  # generated by make_icon.py
    version_file=None,
)
